version: '3'
services:
  ccminer-stak-datapaw:
    image: gardenminer/miner
    ports:
      - "4168:4068"
    environment:
      - ALGO=lyra2v2
      - MINING_POOL=stratum+tcp://pool.datapaw.net:4533
      - USER_NAME=SfvDZZwbb4CJ9DDAuRFsJqFLMWoEzJWHZH.iamsrichai
      - PASSWORD=
      - API_IP=0.0.0.0
      - API_PORT=4068
    volumes:
      - /etc/localtime:/etc/localtime:ro
  ccminer-stak-suprnova:
    image: gardenminer/miner
    ports:
      - "4268:4068"
    environment:
      - ALGO=lyra2rev2
      - MINING_POOL=stratum+tcp://stak.suprnova.cc:7706
      - USER_NAME=SfvDZZwbb4CJ9DDAuRFsJqFLMWoEzJWHZH
      - PASSWORD=
      - API_IP=0.0.0.0
      - API_PORT=4068
    volumes:
      - /etc/localtime:/etc/localtime:ro
  ccminer-xzc-datapaw:
    image: gardenminer/miner
    ports:
      - "4368:4068"
    environment:
      - ALGO=lyra2z
      - MINING_POOL=stratum+tcp://pool.datapaw.net:4553
      - USER_NAME=
      - PASSWORD=
      - API_IP=0.0.0.0
      - API_PORT=4068
    volumes:
      - /etc/localtime:/etc/localtime:ro